version: '3'
services:
    db:
        image: postgres:9.3
        environment:
            POSTGRES_USER: smfuser
            POSTGRES_PASSWORD: smfpass 
            POSTGRES_DB: smfdb
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db

