version: '3'
services:
  db:
    container_name: smf_db
    env_file: db.env
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    container_name: smf_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - smf_data:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true
  smf_data:
    external: true
